# ----------------------- #
#      Main Configs       #
# ----------------------- #

url:           http://blog.jaceklaskowski.pl
title:         Mastering FP and OO with Scala
subtitle:      Making use of functional and object-oriented programming on JVM
author:        Jacek Laskowski
simple_search: https://www.google.com/search
description:   "Recipes for making object-oriented Scala fun(ctional)!"

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
# 2013-11-21
# http://blog.zerosharp.com/removing-the-rss-subscription-icon-from-octopress/
show_feeds: true
subscribe_rss: http://feeds.feedburner.com/MasteringFpWithScala
subscribe_email:
# RSS feeds can list your email address if you like
email:

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root:         /
permalink:    /:year/:month/:day/:title.html
source:       source
destination:  public
plugins:      plugins
code_dir:     downloads/code
category_dir: blog/categories
markdown:     rdiscount
rdiscount:
  extensions:
    - autolink
    - footnotes
    - smart
highlighter: pygments # default python pygments have been replaced by pygments.rb

paginate: 10          # Posts per page on the blog index
paginate_path: "posts/:num"  # Directory base for pagination URLs eg. /posts/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles
excerpt_separator: "<!--more-->"

titlecase: true       # Converts page and post titles to titlecase

# list each of the sidebar modules you want to include, in the order you want them to appear.
# To add custom asides, create files in /source/_includes/custom/asides/ and add them to the list like 'custom/asides/custom_aside_name.html'
default_asides: [asides/recent_posts.html, asides/github.html, custom/asides/ota/twitterOcto.html, asides/delicious.html, custom/asides/coderwall.html, asides/googleplus.html]

# Each layout uses the default asides, but they can have their own asides instead. Simply uncomment the lines below
# and add an array with the asides you want to use.
# blog_index_asides:
# post_asides:
# page_asides:

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user: jaceklaskowski
github_repo_count: 5
github_show_profile_link: true
github_skip_forks: true

# Twitter
twitter_user: jaceklaskowski
twitter_tweet_button: true
twitter_widget_id: 340586331971403776

# Google +1
google_plus_one: true
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user: 117348138300416070551
googleplus_hidden: false

# Pinboard
pinboard_user:
pinboard_count: 3

# Delicious
delicious_user:
delicious_count: 3

# Disqus Comments
disqus_short_name: jaceklaskowski
disqus_show_comment_count: false

# Google Analytics
google_analytics_tracking_id: UA-45999426-1

# Facebook Like
facebook_like: true

# Coderwall
coderwall_user: jaceklaskowski
coderwall_show_endorse_link: true

# LinkedIn
linkedin_user: JacekLaskowski
